const data = [
  {
    email: "thegreentable@gmail.com",
    restaurant_id: "123001",
    device_type: "mobile",
    sent_on: "20-07-24",
    status: "true",
  },
  {
    email: "bistrodelights@gmail.com",
    restaurant_id: "123002",
    device_type: "desktop",
    sent_on: "20-07-25",
    status: "false",
  },
  {
    email: "urbanbites@gmail.com",
    restaurant_id: "123003",
    device_type: "tablet",
    sent_on: "20-07-26",
    status: "true",
  },
  {
    email: "seasidesnacks@gmail.com",
    restaurant_id: "123004",
    device_type: "mobile",
    sent_on: "20-07-27",
    status: "false",
  },
  {
    email: "mountaingrill@gmail.com",
    restaurant_id: "123005",
    device_type: "desktop",
    sent_on: "20-07-28",
    status: "true",
  },
  {
    email: "downtowncafe@gmail.com",
    restaurant_id: "123006",
    device_type: "mobile",
    sent_on: "20-07-29",
    status: "true",
  },
  {
    email: "lakesidelounge@gmail.com",
    restaurant_id: "123007",
    device_type: "tablet",
    sent_on: "20-07-30",
    status: "false",
  },
  {
    email: "gardenbistro@gmail.com",
    restaurant_id: "123008",
    device_type: "mobile",
    sent_on: "20-07-31",
    status: "true",
  },
  {
    email: "rooftopdining@gmail.com",
    restaurant_id: "123009",
    device_type: "desktop",
    sent_on: "20-08-01",
    status: "true",
  },
  {
    email: "goldenhorizons@gmail.com",
    restaurant_id: "123010",
    device_type: "mobile",
    sent_on: "20-08-02",
    status: "false",
  },
  {
    email: "countrysidecuisine@gmail.com",
    restaurant_id: "123011",
    device_type: "tablet",
    sent_on: "20-08-03",
    status: "true",
  },
  {
    email: "riverbankeatery@gmail.com",
    restaurant_id: "123012",
    device_type: "desktop",
    sent_on: "20-08-04",
    status: "false",
  },
  {
    email: "midtownmeals@gmail.com",
    restaurant_id: "123013",
    device_type: "mobile",
    sent_on: "20-08-05",
    status: "true",
  },
  {
    email: "sunsetdine@gmail.com",
    restaurant_id: "123014",
    device_type: "tablet",
    sent_on: "20-08-06",
    status: "true",
  },
  {
    email: "citycornercafe@gmail.com",
    restaurant_id: "123015",
    device_type: "desktop",
    sent_on: "20-08-07",
    status: "false",
  },
  {
    email: "harborview@gmail.com",
    restaurant_id: "123016",
    device_type: "mobile",
    sent_on: "20-08-08",
    status: "true",
  },
  {
    email: "rusticfeast@gmail.com",
    restaurant_id: "123017",
    device_type: "tablet",
    sent_on: "20-08-09",
    status: "false",
  },
  {
    email: "skylinegrill@gmail.com",
    restaurant_id: "123018",
    device_type: "desktop",
    sent_on: "20-08-10",
    status: "true",
  },
  {
    email: "wharfsidewonders@gmail.com",
    restaurant_id: "123019",
    device_type: "mobile",
    sent_on: "20-08-11",
    status: "true",
  },
  {
    email: "starlightcuisine@gmail.com",
    restaurant_id: "123020",
    device_type: "tablet",
    sent_on: "20-08-12",
    status: "false",
  },
  {
    email: "forestflavors@gmail.com",
    restaurant_id: "123021",
    device_type: "mobile",
    sent_on: "20-08-13",
    status: "true",
  },
  {
    email: "palmtreeparadise@gmail.com",
    restaurant_id: "123022",
    device_type: "desktop",
    sent_on: "20-08-14",
    status: "false",
  },
  {
    email: "moonlitmeals@gmail.com",
    restaurant_id: "123023",
    device_type: "tablet",
    sent_on: "20-08-15",
    status: "true",
  },
  {
    email: "sunrisetreats@gmail.com",
    restaurant_id: "123024",
    device_type: "mobile",
    sent_on: "20-08-16",
    status: "true",
  },
  {
    email: "hilltopdelights@gmail.com",
    restaurant_id: "123025",
    device_type: "desktop",
    sent_on: "20-08-17",
    status: "false",
  },
  {
    email: "cobblestonecafe@gmail.com",
    restaurant_id: "123026",
    device_type: "mobile",
    sent_on: "20-08-18",
    status: "true",
  },
  {
    email: "oceanbreezebites@gmail.com",
    restaurant_id: "123027",
    device_type: "tablet",
    sent_on: "20-08-19",
    status: "false",
  },
  {
    email: "pearlplate@gmail.com",
    restaurant_id: "123028",
    device_type: "desktop",
    sent_on: "20-08-20",
    status: "true",
  },
  {
    email: "riversiderest@gmail.com",
    restaurant_id: "123029",
    device_type: "mobile",
    sent_on: "20-08-21",
    status: "true",
  },
  {
    email: "marinemeals@gmail.com",
    restaurant_id: "123030",
    device_type: "tablet",
    sent_on: "20-08-22",
    status: "false",
  },
  {
    email: "vineyardvibes@gmail.com",
    restaurant_id: "123031",
    device_type: "desktop",
    sent_on: "20-08-23",
    status: "true",
  },
  {
    email: "heritagehub@gmail.com",
    restaurant_id: "123032",
    device_type: "mobile",
    sent_on: "20-08-24",
    status: "true",
  },
  {
    email: "maplewood@gmail.com",
    restaurant_id: "123033",
    device_type: "tablet",
    sent_on: "20-08-25",
    status: "false",
  },
  {
    email: "pinesnacks@gmail.com",
    restaurant_id: "123034",
    device_type: "desktop",
    sent_on: "20-08-26",
    status: "true",
  },
  {
    email: "echoesdine@gmail.com",
    restaurant_id: "123035",
    device_type: "mobile",
    sent_on: "20-08-27",
    status: "true",
  },
  {
    email: "lagoonlunch@gmail.com",
    restaurant_id: "123036",
    device_type: "tablet",
    sent_on: "20-08-28",
    status: "false",
  },
  {
    email: "pinehilldiner@gmail.com",
    restaurant_id: "123037",
    device_type: "desktop",
    sent_on: "20-08-29",
    status: "true",
  },
  {
    email: "evergreenbites@gmail.com",
    restaurant_id: "123038",
    device_type: "mobile",
    sent_on: "20-08-30",
    status: "true",
  },
  {
    email: "sunnyfields@gmail.com",
    restaurant_id: "123039",
    device_type: "tablet",
    sent_on: "20-08-31",
    status: "false",
  },
  {
    email: "cedarviewcafe@gmail.com",
    restaurant_id: "123040",
    device_type: "desktop",
    sent_on: "20-09-01",
    status: "true",
  },
  {
    email: "mistymeadows@gmail.com",
    restaurant_id: "123041",
    device_type: "mobile",
    sent_on: "20-09-02",
    status: "true",
  },
  {
    email: "shoresidediner@gmail.com",
    restaurant_id: "123042",
    device_type: "tablet",
    sent_on: "20-09-03",
    status: "false",
  },
  {
    email: "crescentcuisine@gmail.com",
    restaurant_id: "123043",
    device_type: "desktop",
    sent_on: "20-09-04",
    status: "true",
  },
  {
    email: "stargazerdining@gmail.com",
    restaurant_id: "123044",
    device_type: "mobile",
    sent_on: "20-09-05",
    status: "true",
  },
  {
    email: "moonshinerest@gmail.com",
    restaurant_id: "123045",
    device_type: "tablet",
    sent_on: "20-09-06",
    status: "false",
  },
  {
    email: "crimsoncafe@gmail.com",
    restaurant_id: "123046",
    device_type: "desktop",
    sent_on: "20-09-07",
    status: "true",
  },
  {
    email: "orchardfeasts@gmail.com",
    restaurant_id: "123047",
    device_type: "mobile",
    sent_on: "20-09-08",
    status: "true",
  },
  {
    email: "wildflowercuisine@gmail.com",
    restaurant_id: "123048",
    device_type: "tablet",
    sent_on: "20-09-09",
    status: "false",
  },
  {
    email: "serenitymeals@gmail.com",
    restaurant_id: "123049",
    device_type: "desktop",
    sent_on: "20-09-10",
    status: "true",
  },
  {
    email: "autumndelights@gmail.com",
    restaurant_id: "123050",
    device_type: "mobile",
    sent_on: "20-09-11",
    status: "true",
  },
  {
    email: "azureeats@gmail.com",
    restaurant_id: "123051",
    device_type: "tablet",
    sent_on: "20-09-12",
    status: "false",
  },
  {
    email: "trailside@gmail.com",
    restaurant_id: "123052",
    device_type: "desktop",
    sent_on: "20-09-13",
    status: "true",
  },
  {
    email: "cherrysnacks@gmail.com",
    restaurant_id: "123053",
    device_type: "mobile",
    sent_on: "20-09-14",
    status: "true",
  },
  {
    email: "royaloak@gmail.com",
    restaurant_id: "123054",
    device_type: "tablet",
    sent_on: "20-09-15",
    status: "false",
  },
  {
    email: "windsormeals@gmail.com",
    restaurant_id: "123055",
    device_type: "desktop",
    sent_on: "20-09-16",
    status: "true",
  },
];

export default data;
