export const data = [
  {
    service_no: "INC4686404",
    description: "Term 1 CLP not printing -was pos",
    day: "Today",
    status: "Open",
  },
  {
    service_no: "INC4679386",
    description: "CT -NC Missing Labor Hours for 5/25",
    day: "3",
    status: "Closed",
  },
  {
    service_no: "INC3749623",
    description: "Term 1 CLP not printing -was pos",
    day: "1",
    status: "In Progress",
  },
  {
    service_no: "INC4698762",
    description: "Term 1 CLP not printing -was pos",
    day: "2",
    status: "Open",
  },
  {
    service_no: "INC4342313",
    description: "Term 1 CLP not printing -was pos",
    day: "4",
    status: "In Progress",
  },
  {
    service_no: "INC4675422",
    description: "Term 1 CLP not printing -was pos",
    day: "7",
    status: "Closed",
  },
  {
    service_no: "INC4686511",
    description: "Term 1 CLP not printing -was pos",
    day: "2",
    status: "Open",
  },
  {
    service_no: "INC4686723",
    description: "Term 1 CLP not printing -was pos",
    day: "3",
    status: "In Progress",
  },
  {
    service_no: "INC4686999",
    description: "Term 1 CLP not printing -was pos",
    day: "1",
    status: "Open",
  },
  {
    service_no: "INC4686812",
    description: "Term 1 CLP not printing -was pos",
    day: "5",
    status: "Open",
  },
  {
    service_no: "INC4686221",
    description: "Term 1 CLP not printing -was pos",
    day: "3",
    status: "Closed",
  },
  {
    service_no: "INC4686456",
    description: "Term 1 CLP not printing -was pos",
    day: "4",
    status: "In Progress",
  },
  {
    service_no: "INC4686686",
    description: "Term 1 CLP not printing -was pos",
    day: "6",
    status: "Open",
  },
  {
    service_no: "INC4686231",
    description: "Term 1 CLP not printing -was pos",
    day: "7",
    status: "Closed",
  },
  {
    service_no: "INC4679232",
    description: "Term 1 CLP not printing -was pos",
    day: "9",
    status: "Closed",
  },
  {
    service_no: "INC3746121",
    description: "Term 1 CLP not printing -was pos",
    day: "2",
    status: "Closed",
  },
  {
    service_no: "INC4672211",
    description: "Issue present",
    day: "1",
    status: "In Progress",
  },
  {
    service_no: "INC3881223",
    description: "Printer 1 CLP not printing",
    day: "3",
    status: "Closed",
  },
];
